blank_issues_enabled: true
contact_links:
  - name: Issue with ASP.NET Core
    url:  https://github.com/dotnet/aspnetcore/issues/new/choose
    about: Please open issues relating to ASP.NET Core in dotnet/aspnetcore.
  - name: Issue with .NET runtime or core .NET libraries
    url:  https://github.com/dotnet/runtime/issues/new/choose
    about: Please open issues with the .NET runtime or core .NET libraries in dotnet/runtime.
  - name: Issue with .NET SDK
    url:  https://github.com/dotnet/sdk/issues/new/choose
    about: Please open issues relating to the .NET SDK in dotnet/sdk.
  - name: Issue with Entity Framework
    url:  https://github.com/dotnet/efcore/issues/new/choose
    about: Please open issues relating to Entity Framework in dotnet/efcore.
  - name: Issue with Roslyn compiler
    url:  https://github.com/dotnet/roslyn/issues/new/choose
    about: Please open issues relating to the Roslyn .NET compiler in dotnet/roslyn.
  - name: Issue with Windows Forms
    url:  https://github.com/dotnet/winforms/issues/new/choose
    about: Please open issues relating to Windows Forms in dotnet/winforms.
  - name: Issue with WPF
    url:  https://github.com/dotnet/wpf/issues/new/choose
    about: Please open issues relating to WPF in dotnet/wpf.
  - name: Issue with .NET Framework
    url:  https://developercommunity.visualstudio.com/spaces/61/index.html
    about: Please open issues relating to the .NET Framework (rather than .NET Core or .NET 5+) in Developer Community
